#define RETA_CURTA 'C'
#define CURVA_ABERTA 'A'
#define CURVA_FECHADA 'F'
#define RETA_NORMAL 'R'
#define RETA_LONGA 'L'

char trechos_tipo[] = { 
    RETA_NORMAL,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_FECHADA,
    RETA_CURTA,
    CURVA_FECHADA,
    RETA_CURTA,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_FECHADA,
    RETA_CURTA,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_FECHADA,
    RETA_NORMAL,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_FECHADA,
    RETA_CURTA,
    CURVA_ABERTA,
    RETA_CURTA,
    CURVA_FECHADA,
    CURVA_FECHADA,
    CURVA_FECHADA,
    RETA_LONGA
};
