#include <Arduino.h>
#include <Wire.h>

#define MAIN2 PA2 //MOTOR DA ESQUERDA SENTIDO ANTI-HORÁRIO
#define MAIN1 PB13 //MOTOR DA ESQUERDA SENTIDO HORÁRIO

#define MBIN1 PA7 //MOTOR DA DIREITA SENTIDO ANTI-HORÁRIO
#define MBIN2 PB0 //MOTOR DA DIREITA SENTIDO HORÁRIO

#define PWMA PB8
#define PWMB PA1

#define LED1 PA10
#define LED2 PC13

#define BTN1 PB3
#define BTN2 PB4

#define ENC1A PB15 //ENCODER DA ESQUERDA
#define ENC1B PC15 //ENCODER DA ESQUERDA

#define ENC2A PB5 //ENCODER DA DIREITA
#define ENC2B PB11 //ENCODER DA DIREITA

#define bluetooth_activate 1

